#!/bin/sh
set -e

# write the .env config
{ \
    echo API_V1_PREFIX="$API_V1_PREFIX"; \
    echo DEBUG="$DEBUG"; \
    echo PROJECT_NAME="$PROJECT_NAME"; \
    echo VERSION="$VERSION"; \
    echo DESCRIPTION="$DESCRIPTION"; \
    echo DB_ASYNC_CONNECTION_STR="postgresql+asyncpg://$POSTGRES_SERVER:$POSTGRES_POART"; \
    echo DB_EXCLUDE_TABLES="$DB_EXCLUDE_TABLES"; \
} > /vyce-backend/.env

exec "$@"