#!/bin/bash
set -e

# config .env and connect to database
{ \
    echo API_V1_PREFIX="$API_V1_PREFIX"; \
    echo DEBUG="$DEBUG"; \
    echo PROJECT_NAME="$PROJECT_NAME"; \
    echo VERSION="$VERSION"; \
    echo DESCRIPTION="$DESCRIPTION"; \
    echo DB_ASYNC_CONNECTION_STR="postgresql+asyncpg://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE"; \
    echo DB_ASYNC_TEST_CONNECTION_STR="postgresql+asyncpg://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE"; \
    echo DB_EXCLUDE_TABLES="$DB_EXCLUDE_TABLES"; \
} > /vyce-backend/.env

alembic upgrade head

exec "$@"
