apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes-app
  labels:
    app: heroes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroes-app
  template:
    metadata:
      labels:
        app: heroes-app
    spec:
      imagePullSecrets:
        - name: registry-key
      containers:
        - name: heroes-app
          image: ghcr.io/micha-aucoin/hero:sha-2540bf6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: heroes-pg-secret
                  key: postgresql-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: heroes-pg-secret
                  key: postgresql-password
            - name: POSTGRES_SERVER
              valueFrom:
                configMapKeyRef:
                  name: heroes-pg-configmap
                  key: database_url
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: heroes-pg-configmap
                  key: database
---
apiVersion: v1
kind: Service
metadata:
  name: heroes-app-service
spec:
  type: LoadBalancer
  selector:
    app: heroes-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000
