"""add quotes table

Revision ID: 066536152e39
Revises: 886322ad66ff
Create Date: 2023-01-30 09:05:04.947865

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '066536152e39'
down_revision = '886322ad66ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('Open', sa.Float(), nullable=False),
    sa.Column('High', sa.Float(), nullable=False),
    sa.Column('Low', sa.Float(), nullable=False),
    sa.Column('Close', sa.Float(), nullable=False),
    sa.Column('Volume', sa.Integer(), nullable=True),
    sa.Column('Dividends', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_quotes'))
    )
    op.create_index(op.f('ix_quotes_Dividends'), 'quotes', ['Dividends'], unique=False)
    op.create_index(op.f('ix_quotes_Volume'), 'quotes', ['Volume'], unique=False)
    op.create_index(op.f('ix_quotes_date'), 'quotes', ['date'], unique=False)
    op.create_index(op.f('ix_quotes_uuid'), 'quotes', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_uuid'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_date'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_Volume'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_Dividends'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
